# Generated by Django 5.2.4 on 2025-07-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(default="Awaiting shipment", max_length=50),
        ),
    ]
